version: '3.8'

services:
  detectron_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Ganti port 5000 ke 8000
    environment:
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=8000
